configMap:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "roboshop-dev.cohi6q8wqf1j.us-east-1.rds.amazonaws.com" #change rds volume end point
deployment:
  replicas: "1"
  imageName: "mamatar/shipping"
  imageVersion: "1.4.0"